"""requirement status logs

Revision ID: d71563e372e1
Revises: 375ae54f5c05
Create Date: 2026-08-15 14:55:40.798762

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd71563e372e1'
down_revision: Union[str, None] = '375ae54f5c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirement_status_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirement_status_logs', schema=None) as batch_op:
        batch_op.create_index('ix_status_logs_created', ['created_at', 'to_status'], unique=False)
        batch_op.create_index('ix_status_logs_requirement', ['requirement_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirement_status_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_status_logs_requirement')
        batch_op.drop_index('ix_status_logs_created')

    op.drop_table('requirement_status_logs')
    # ### end Alembic commands ###
